add glibc

diff --git a/oraclejdk/jdk-8/Dockerfile b/oraclejdk/jdk-8/Dockerfile
--- a/oraclejdk/jdk-8/Dockerfile
+++ b/oraclejdk/jdk-8/Dockerfile
@@ -32,25 +32,45 @@ ENV JAVA_HOME "${JAVA_JVM_PATH}/${JAVA_JDK}"
 ENV PATH $PATH:$JAVA_HOME/bin
 # ENV PATH $PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/bin
 
+ARG GLIBC_VERSION="2.30-r0"
+ARG GLIBC_REPO="https://github.com/sgerrand/alpine-pkg-glibc"
+ARG GLIBC_DOWNLOAD="${GLIBC_REPO}/releases/download/${GLIBC_VERSION}"
+ARG GLIBC_PACKAGES="glibc-${GLIBC_VERSION}.apk glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk"
+ARG GLIBC_PATH="/usr/glibc-compat"
+
 RUN set -eux; \
 	apk -U upgrade; \
-    apk add --no-cache --virtual .java-deps curl; \
-	wget -O "${JAVA_TMP}" "--header=Cookie: oraclelicense=accept-securebackup-cookie" "${JAVA_ASSET_URL}" && \
+    apk add --no-cache --virtual .java-deps libstdc++ curl; \
+# Required glibc dependencies
+	for pkg in "${GLIBC_PACKAGES}"; do wget -O "/tmp/${pkg}" "${GLIBC_DOWNLOAD}/${pkg}"; done && \
+	apk add --allow-untrusted /tmp/*.apk && \
+    rm -v /tmp/*.apk; \
+    ( ${GLIBC_PATH}/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true ); \
+    echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh; \
+    ${GLIBC_PATH}/sbin/ldconfig /lib ${GLIBC_PATH}/lib; \
+    echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf; \
+# Install java from oracle
+    wget -O "${JAVA_TMP}" "--header=Cookie: oraclelicense=accept-securebackup-cookie" "${JAVA_ASSET_URL}" && \
 	sha256sum "${JAVA_TMP}"; \
     JAVA_PACKAGE_SHA256=$(curl -sSL "${JAVA_CHECKSUM}" | grep -E "${JAVA_ASSET}" | grep -Eo '(sha256: )[^<]+' | cut -d: -f2 | xargs) && \
     echo "${JAVA_PACKAGE_SHA256}  ${JAVA_TMP}" | sha256sum -c; \
 	mkdir -p "${JAVA_HOME}"; \
     tar --extract --file "${JAVA_TMP}" --directory "${JAVA_HOME}" --strip-components 1; \
+	ln -s "$JAVA_HOME/bin/"* "/usr/bin/"; \
 	ls -lp "${JAVA_JVM_PATH}"; \
+# Clean up
 	# find ${JAVA_HOME} -maxdepth 1 -mindepth 1 | grep -v jre | xargs rm -rf && \
-    apk del --no-network .java-deps; \
+	apk del glibc-i18n; \
+	apk del --no-network .java-deps; \
 	rm -rf /tmp/* /var/cache/apk/*; \
 	# chown -R root:root ${JAVA_HOME}; \
 # Java smoke test
 	which java; \
-	java -version; \
+	# java -version; \
 	which javac; \
-	ls -lp "${JAVA_HOME}/jre/bin"
+	ls -lp "${JAVA_HOME}/lib"; \
+	ls -lp "${JAVA_HOME}/jre/bin"; \
+	ls -lp "${JAVA_HOME}/jre/lib"
 	# javac -version
 
 # https://docs.oracle.com/javase/10/tools/jshell.htm
